package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func Generate(projectName string, quantitative map[string]string, qualitative map[string]string, anomaly map[string]string) string {
	now := time.Now().Format("2006-01-02 15:04 UTC")
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Public Goods Evaluation Report: %s\n", projectName))
	b.WriteString(fmt.Sprintf("*Generated: %s*\n\n", now))

	if len(quantitative) > 0 {
		b.WriteString("## Quantitative Analysis\n\n")
		if v, ok := quantitative["composite_score"]; ok {
			b.WriteString(fmt.Sprintf("**Composite Score:** %s/100\n\n", v))
		}
		if v, ok := quantitative["cluster"]; ok {
			b.WriteString(fmt.Sprintf("**Cluster Group:** %s\n\n", v))
		}
		b.WriteString("| Metric | Value |\n|--------|-------|\n")
		for k, v := range quantitative {
			if k != "composite_score" && k != "cluster" {
				b.WriteString(fmt.Sprintf("| %s | %s |\n", k, v))
			}
		}
		b.WriteString("\n")
	}

	if len(anomaly) > 0 {
		b.WriteString("## Funding Anomaly Detection\n\n")
		for k, v := range anomaly {
			b.WriteString(fmt.Sprintf("- **%s:** %s\n", k, v))
		}
		b.WriteString("\n")
	}

	if eval, ok := qualitative["evaluation"]; ok {
		b.WriteString("## Qualitative Analysis\n\n")
		b.WriteString(eval)
		b.WriteString("\n\n")
		if m, ok := qualitative["model"]; ok {
			b.WriteString(fmt.Sprintf("*Analysis by: %s/%s*\n\n", qualitative["provider"], m))
		}
	}

	b.WriteString("---\n*Report generated by Public Goods Analyst — The Synthesis Hackathon*\n")

	content := b.String()
	saveReport(projectName, content)
	return content
}

func GenerateComparison(comparison, model, prov string, count int) string {
	now := time.Now().Format("2006-01-02 15:04 UTC")
	var b strings.Builder
	b.WriteString("# Public Goods Project Comparison Report\n")
	b.WriteString(fmt.Sprintf("*Generated: %s*\n", now))
	b.WriteString(fmt.Sprintf("*Projects compared: %d*\n\n", count))
	b.WriteString("## Comparative Analysis\n\n")
	b.WriteString(comparison)
	b.WriteString("\n\n---\n*Report generated by Public Goods Analyst — The Synthesis Hackathon*\n")

	content := b.String()
	saveReport("comparison", content)
	return content
}

func saveReport(name, content string) {
	os.MkdirAll("reports", 0o755)
	safe := strings.Map(func(r rune) rune {
		if r == ' ' || r == '/' {
			return '_'
		}
		return r
	}, strings.ToLower(name))
	if len(safe) > 50 {
		safe = safe[:50]
	}
	ts := time.Now().Format("20060102_150405")
	path := filepath.Join("reports", fmt.Sprintf("%s_%s.md", safe, ts))
	os.WriteFile(path, []byte(content), 0o644)
}
